#!/usr/bin/env bash

build_type() {
	dir="$1"
	dirmod=${dir//\//.}
	dirident=${dir//\//_}

	cat <<-LUA
		---@class ${dirmod}
		local ${dirident} = {}
	LUA
	while read -r fullname; do
		filename=$(basename "$fullname")
		modname=${filename%.*}
		if [[ $modname == "init" ]]; then
			continue
		fi
		cat <<-LUA
			${dirident}["${modname}"] = require("${dirmod}.${modname}")
		LUA
	done < <(find "lua/$dir" -type f | sort)
}

{
	echo "---@meta _"
	echo "---This file is @generated by update_types.sh. Do not modify it directly."
	echo "-- stylua: ignore start"

	echo && build_type meowim/plugins

	echo && build_type meowim/plugins/mini
} >lua/meowim/types.lua
